### ISSUE TITLE
Mention the latest version as 1.10.0

### ISSUE THREAD

**Issue by karuppiah7890** [laviua/komock#35]
I see that we can get release info from this page : https://github.com/laviua/komock/releases/latest , but it shows version as `1.10` which is not the exact version present in the maven central repo . After some checking I realized the complete correct version is `1.10.0`, I think it would be useful to put this in the readme, or change the release info in the releases or completely change the release including the tag?

**Comment by laviua** [comment]
thanks, i've fixed release version
